name: st10042-assembly
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pandas
  - requests
  - fastp
  - spades
  - unicycler
  - quast
  - seqkit
  - pigz
  - bowtie2
  - samtools
